name: click_mockup
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.5
  expandable: ^5.0.1
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  list_tile_switch: ^1.0.0
  loading_animation_widget: ^1.2.1
  calendar_date_picker2: ^1.0.6

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mock/
